<?php

?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"><?php echo $this->getButtonsHtml() ?></div>
        <h4 class="fieldset-legend head-delivery-date"><?php echo $this->__(' Source Channel ') ?></h4>
    </div>
    <div class="fieldset">
        <select name="sourcechannel" id="sourcechannel">
            <option value="">--Please Select--</option>
        <?php 
        $sources = $this->getDropdown();
        foreach($sources as $source){
            echo "<option value='";
            echo $source->getChannelCode();
            echo "'>";
            echo $source->getChannelText();
            echo "</option>";
        }
        ?>
        </select>
    </div>
</div>