<?php
/**
 * Veritrans VT Direct virtual account Model Standard
 *
 * @category   Mage
 * @package    bcava/form.phtml
 * this template is rendered when Veritrans payment method is chosen. This is description about Veritrans Payment Method
 */
?>

<ul class="form-list checkout-agreements" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none; margin-buttom:20px;">
    
	<li><img src="<?php echo $this->getSkinUrl('images/paymentmethod/indomaret.png') ?>" style= "padding-left:10px !important; padding-top:0px;width:100px;"/>
	     
      <?php if ($instructions = $this->getInstructions()): ?>      
            <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content" style= "padding-left:10px !important;">
                <?php echo nl2br($instructions) ?>
            </div>
        
       <?php endif; ?>
    </li>
	
</ul>

