<?php
/**
 * Veritrans VT Direct adminhtml info template
 *
 * @category   Mage
 * @package    vtdirect/info.phtml
 * @author     denny
 * this template is used for payment method information at the right side, in progress bar.
 */
?>

<?php 
echo $this->escapeHtml($this->getMethod()->getTitle());
$_order = $this->getOrder();
$detail = $this->getVadetail($_order->getId());
echo "<br/>Indomaret Code: <b>".$detail[0]['va_number']."</b><br/>";
echo "Expired date: ".$detail[0]['expire_date'];